{% set name = "python-rapidjson" %}
{% set version = "1.22" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name|replace('-', '_') }}-{{ version }}.tar.gz
  sha256: ebe16d1f92a6e325f319c5d22f751f2127840fd6fb4a1ed6e0749e7873ff03f3

build:
  number: 0
  skip: true  # [py<36]
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  build:
    - {{ stdlib('c') }}
    - {{ compiler('cxx') }}
  host:
    - python
    - pip
    - wheel
    - setuptools
    - packaging
  run:
    - python

test:
  source_files:
    - tests
  imports:
    - rapidjson
  requires:
    - pip
    - pytest >=8.4.1
    - pytz >=2025.2
  commands:
    - pip check
    - python -c "from importlib.metadata import version; assert(version('{{ name }}')=='{{ version }}')"
    - pytest -v tests

about:
  home: https://github.com/python-rapidjson/python-rapidjson
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Python wrapper around rapidjson
  description: |
    Python wrapper around RapidJSON. RapidJSON is an extremely fast C++ json serialization library.
    We do not support legacy python versions, you will need to upgrade to Python 3 to use this library.
  doc_url: https://python-rapidjson.readthedocs.io
  dev_url: https://github.com/python-rapidjson/python-rapidjson

extra:
  recipe-maintainers:
    - SylvainCorlay
    - hajapy
