travis:
  secure:
    BINSTAR_TOKEN: Y3MN0m8rII8lWUtWZp2yI43ypeVi8UXb3IZD3Rso8H4j+cbUxfVySnGSii1NNi55zjaNym3HRFd5s2egzC/6CGGz/c/6HotsKGcQhKPCPnMPLhvlZLOTiuo4Tlm1mmP375amteJN3oLpvLSTILseMnjKupPbTOJQkBzVklz/tT7t2WfP8LTfZ7ivkUrpSSawN/BS0+qHWiZdWP/GohHG4h314r+YXtpNEV5M8ctxh1HeTgT5ibrdveMQOHezWJ3wdy55N954doKXiQ7TcH+RfOYZ1zLceHu5lESQ2WAA3h3qzBc0YA7vpUAwbuiJx289oQF7i41UvERLO8SODDguE/JrECFNIzmZ0DhDvkXCKbnUsXld5aB3tKu7iKoCYIFYoDnRwcphjivXRCtlZkFN7fgqVxouc+UDtPyaSWMXwg6GDAXXlGkxJRzsTK/N27+n/ZOl3DPQulyqvebUTg3gsYY7Rh7thJ4yBXfqYBUep31WWLuS0L+/wsJheny0cfPq778pso/bSzZLw1PXanI5lLKy7gKQri8I5DmiDXfzsoS633c1dOTSrrZ4Y5gH1CZWwJhLmDat5RrONwn7e/u2TV55UfpdMR2fTKrq9zlfIcMtIznDmPA/6Y9ue+aMToX5aNlGBhiSDG7nsIc6Z5HVLa0EF+awnT7a78hKCrPfWMc=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
