travis:
  secure:
    BINSTAR_TOKEN: aQRxqTCi6Xv1sfdwFqttBSYpq3MuK8AzISZ1ht6F6TBQN8fHRw+RR48dQrDc0UHZD4j+a0AbyOHf9nDNMXY9f5cPIe9z4vL3E1J7x5p2Yd1NsK0Htda2J63BktjUeHM58LeF1DlEjTlERDiP5eY83wJpZKZZqQYBQuFoLb5+xpfFQyKjRYZK1WwBXvxjw6UFWp3WzV7xLn2FXKEEemQEX63r6AoonaZQguGi07iktCGPnPkVD81urqT53gvNgKMiXfZ4vZNBi6VfIsGLTGGOO9kc8nzlO1OMbEf8SPCyO0EW5cCUyjY/n7mUYxeUIqBCpkFlHLhsOgtGlVYohPiAM7uYjfJPX93TJlkc6nWQIDNGEuRxVgqyWcxcgX+a2YLri0Wku5j7M4s9yMIT4Wmj/ZRZaIg/D1A/kVu4exWF/lp1bCoG8VT7VcyY1uuCzMAvur0vX1VxRwMcZx4B4z3NU2H6u3JZ/vIHwww6k19PzUpezUmXnwDLAl9Q8s+zr3VhzruyQujYMjREP0e6nhSnD/tw5khB1vNiJBALgQNuBLJE8RdHZMBNKbMf18Rsm0sOIig0BkGERW6AWvuOHUTSbq5+C1E58c5I58b7X5D9e4DFXsxT5qUIrBwnWVHrAGlzO/iNnbsAnLZGATIcaWv86/C/yWfBImNTTEGBgeNarBQ=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
